In [3]:
import pandas

In [4]:
pandas.__version__

'1.4.4'

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [13]:
sales_data = pd.read_csv('Online_Cars_Sale_Marketplace.csv')

In [16]:
pd.read_csv('Online_Cars_Sale_Marketplace.csv')

,Year,Make,Model,Used/New,Price,ConsumerRating,ConsumerReviews,SellerType,SellerName,SellerRating,...,InteriorColor,Drivetrain,MinMPG,MaxMPG,FuelType,Transmission,Engine,VIN,Stock#,Mileage
0,2019,Toyota,Sienna SE,Used,"$39,998",4.6,45,Dealer,CarMax Murrieta - Now offering Curbside Pickup...,3.3,...,Black,Front-wheel Drive,19,27,Gasoline,8-Speed Automatic,3.5L V6 24V PDI DOHC,5TDXZ3DC2KS015402,22998646,29403
1,2018,Ford,F-150 Lariat,Used,"$49,985",4.8,817,Dealer,Giant Chevrolet,4.8,...,Black,Four-wheel Drive,19,24,Gasoline,10-Speed Automatic,3.5L V6 24V PDI DOHC Twin Turbo,1FTEW1EG2JFD44217,22418A,32929
2,2017,RAM,1500 Laramie,Used,"$41,860",4.7,495,Dealer,Gill Auto Group Madera,4.6,...,Black,Four-wheel Drive,15,21,Gasoline,8-Speed Automatic,5.7L V8 16V MPFI OHV,1C6RR7VT5HS842283,NG277871G,23173
3,2021,Honda,Accord Sport SE,Used,"$28,500",5.0,36,Dealer,AutoSavvy Las Vegas,4.6,...,â€“,Front-wheel Drive,29,35,Gasoline,Automatic CVT,1.5L I4 16V GDI DOHC Turbo,1HGCV1F49MA038035,54237,10598
4,2020,Lexus,RX 350,Used,"$49,000",4.8,76,Dealer,Lexus of Henderson,4.8,...,Birch,Front-wheel Drive,20,27,Gasoline,8-Speed Automatic,3.5L V6 24V PDI DOHC,2T2AZMAA8LC156270,HDT4181A,28137
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9374,2019,Subaru,Crosstrek 2.0i Premium,Used,"$27,374",4.7,205,Dealer,Bertera Subaru of West Springfield,4.4,...,Gray,All-wheel Drive,27,33,Gasoline,Automatic CVT,2.0L H4 16V GDI DOHC,JF2GTADC4KH318032,220502A,15606
9375,2019,Audi,Q8 3.0T Premium,Used,"$61,998",4.8,27,Dealer,Autobahn USA Westborough,4.8,...,Black,All-wheel Drive,17,22,Hybrid,8-Speed Automatic,3.0L V6 24V GDI DOHC Turbo Hybrid,WA1AVAF14KD015389,AB4719,46855
9376,2017,Buick,Enclave Leather,Used,"$26,944",4.8,137,Dealer,Tulley Automotive Group,4.7,...,Ebony,All-wheel Drive,15,22,Gasoline,6-Speed Automatic,3.6L V6 24V GDI DOHC,5GAKVBKD4HJ190334,B221381B,62649
9377,2019,Subaru,Forester Premium,Used,"$28,568",4.7,279,Dealer,Ira Subaru,4.4,...,Black,All-wheel Drive,26,33,Gasoline,Automatic CVT,2.5L H4 16V GDI DOHC,JF2SKAGC9KH423450,KH423450,30760
9378,2019,Hyundai,Santa Fe Ultimate 2.4,Used,"$32,091",4.8,204,Dealer,Route 44 Hyundai,4.4,...,Black,All-wheel Drive,21,27,Gasoline,8-Speed Automatic,2.4L I4 16V GDI DOHC,5NMS5CAD1KH002128,H48345,41645

In [17]:
sales_data['SellerType']

0       Dealer
1       Dealer
2       Dealer
3       Dealer
4       Dealer
         ...
9374    Dealer
9375    Dealer
9376    Dealer
9377    Dealer
9378    Dealer
Name: SellerType, Length: 9379, dtype: object

In [18]:
data['SellerType'].value_counts()

Dealer     9339
Private      40
Name: SellerType, dtype: int64

In [21]:
Dealer = sales_data.loc[(sales_data['SellerType'] == "Dealer"), ['SellerType','Year','Make','Model','Used/New','Price']]
Dealer

     SellerType  Year     Make                   Model Used/New    Price
0        Dealer  2019   Toyota               Sienna SE     Used  $39,998
1        Dealer  2018     Ford            F-150 Lariat     Used  $49,985
2        Dealer  2017      RAM            1500 Laramie     Used  $41,860
3        Dealer  2021    Honda         Accord Sport SE     Used  $28,500
4        Dealer  2020    Lexus                  RX 350     Used  $49,000
...         ...   ...      ...                     ...      ...      ...
9374     Dealer  2019   Subaru  Crosstrek 2.0i Premium     Used  $27,374
9375     Dealer  2019     Audi         Q8 3.0T Premium     Used  $61,998
9376     Dealer  2017    Buick         Enclave Leather     Used  $26,944
9377     Dealer  2019   Subaru        Forester Premium     Used  $28,568
9378     Dealer  2019  Hyundai   Santa Fe Ultimate 2.4     Used  $32,091

[9339 rows x 6 columns]

In [22]:
Dealer = sales_data.loc[(sales_data['SellerType'] == "Private"), ['SellerType','Year','Make','Model','Used/New','Price']]
Dealer

,SellerType,Year,Make,Model,Used/New,Price
31,Private,2016,Honda,Odyssey EX-L,Used,"$28,999"
39,Private,2017,Land,Rover Range Rover Evoque SE Premium,Used,"$34,555"
43,Private,2013,INFINITI,G37 x,Used,"$17,300"
45,Private,2017,Tesla,Model S 75,Used,"$47,000"
56,Private,2017,Land,Rover Range Rover Sport 3.0L Supercharged HSE ...,Used,"$53,000"
65,Private,2020,Tesla,Model X Performance,Used,"$122,222"
156,Private,2002,BMW,540 i,Used,"$22,900"
231,Private,2021,BMW,X5 PHEV xDrive45e,Used,"$71,000"
235,Private,2019,Mercedes-Benz,GLC 300 Base 4MATIC,Used,"$37,500"
253,Private,2017,Alfa,Romeo Giulia Ti,Used,"$29,900"
416,Private,2014,Mercedes-Benz,E-Class E 350,Used,"$21,500"
432,Private,2021,Mazda,CX-5 Grand Touring,Used,"$34,590"
436,Private,2014,Lincoln,MKZ Base,Used,"$17,900"
574,Private,2016,Ford,Explorer Limited,Used,"$22,000"
583,Private,2021,Jeep,Grand Cherokee 80th Anniversary,Used,"$45,700"
812,Private,2019,Ford,F-150 Raptor,Used,"$70,000"
862,Private,2017,GMC,Acadia Denali,Used,"$32,000"
908,Private,2021,Tesla,Model 3 Long Range,Used,"$58,000"
1052,Private,2021,Tesla,Model 3 Performance,Used,"$68,000"
1288,Private,2014,Hyundai,Veloster Turbo,Used,"$9,599"
1350,Private,2008,Chevrolet,Silverado 2500 LTZ H/D Crew Cab,Used,"$25,000"
1366,Private,2013,Ford,Focus Titanium,Used,"$8,000"
1504,Private,2020,Honda,Odyssey EX-L w/Navigation/RES,Used,"$35,500"
1730,Private,2020,RAM,1500 Limited,Used,"$62,000"
2153,Private,2020,Lexus,ES 350 Base,Used,"$41,500"
2428,Private,2017,Honda,Accord Sport SE,Used,"$18,950"
2593,Private,2006,Chevrolet,Impala LT,Used,"$2,300"
2773,Private,2014,Ford,Explorer Limited,Used,"$24,500"
3632,Private,2017,Chevrolet,Silverado 1500 LS,Used,"$29,000"
4003,Private,2014,Ford,Explorer Limited,Used,"$24,500"
4486,Private,2008,Porsche,911 Carrera 4 Coupe,Used,"$47,000"
4622,Private,2021,Volvo,XC90 T6 Momentum,Used,"$54,900"
4900,Private,2003,Mercedes-Benz,SL-Class SL500 Roadster,Used,"$11,999"
4939,Private,2006,Jeep,Commander Limited,Used,"$6,999"
5125,Private,2014,Buick,LaCrosse Premium 1,Used,"$21,995"
5234,Private,2021,Toyota,Highlander XLE,Used,"$48,500"
6631,Private,2017,Alfa,Romeo Giulia Ti,Used,"$29,900"
7225,Private,2021,Tesla,Model 3 Performance,Used,"$71,995"
8350,Private,2017,Mercedes-Benz,GLA 250 Base,Used,"$30,400"
8957,Private,2015,Toyota,RAV4 Limited,Used,"$22,000"